name: linux_game_tweaks
description: Ferramenta para ajustes de jogos no Linux.

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  yaru: 5.2.1
  yaru_window: 0.2.1+1
  ubuntu_widgets: 0.7.0
  ubuntu_logger: 0.2.0
  handy_window: 0.4.0
  desktop_notifications: 0.6.3
  gsettings: 0.2.8
  snapd: 0.6.4
  snapcraft_launcher: 0.1.0
  bluez: 0.8.2
  collection: 1.18.0
  xdg_directories: 1.1.0
  path_provider: 2.1.4
  package_info_plus: 8.0.2
  file_selector_linux: 0.9.3
  file_selector: 1.0.3
  file: 7.0.0
  filesize: 2.0.1
  path: 1.9.0
  dio: 5.7.0
  connectivity_plus: 6.0.5
  url_launcher: ^6.3.0
  gtk: 2.1.0
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  change_case: 2.1.0
  easy_debounce: 2.0.3
  intl: 0.19.0
  get_it: 8.0.0
  watch_it: 1.5.1
  intl_utils: 2.8.7
  syntax_highlight: 0.4.0
  shared_preferences: 2.3.2
  vdf: 1.1.0
  result_dart: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.13
  custom_lint: 0.6.7
  freezed: 2.5.7
  json_serializable: 6.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/alternative_apps_db.json
    - assets/links_db.json
    - assets/recommended_apps_db.json


flutter_intl:
  enabled: tr
  class_name: S
  main_locale: pt_BR
  arb_dir: lib/l10n
  output_dir: lib/generated