display_name: Linux Game Tweaks

icon: assets/linux_game_tweaks.png

generic_name: Ferramenta para ajustes de jogos no Linux.

metainfo: linux/packaging/flatpak/io.github.pedroermarinho.linux_game_tweaks.yml

supported_mime_type:
  - application/x-ms-dos-executable
  - application/x-msi
  - application/x-ms-shortcut

keywords:
  - linux
  - game
  - tweaks

categories:
  - Utility
  - Game
  - System
  - Settings

startup_notify: true

include: []