display_name: Linux Game Tweaks
package_name: linux_game_tweaks

maintainer:
  name: Pedro Marinho
  email: pedroermarinho@gmail.com

priority: optional
section: x11
essential: false
icon: assets/512x512.png
metainfo: io.github.pedroermarinho.linux_game_tweaks

supported_mime_type:
  - application/x-ms-dos-executable
  - application/x-msi
  - application/x-ms-shortcut

keywords:
  - linux
  - game
  - tweaks

categories:
  - Utility
  - Game
  - System
  - Settings

startup_notify: true
